### ISSUE TITLE
Searching

### ISSUE THREAD

**Issue by microcian** [codemybrainsout/PlaceSearchDialog#1]
Hi, can i search within a particular area ?? suppose with in a geofence or ploylines ?? if not can we set Priority of searching ?

**Comment by codemybrainsout** [comment]
Hi, Adding custom layout bounds isn't supported yet. I'll try to add it in the upcoming versions.

**Comment by braulio94** [comment]
Same here

**Comment by ahulr** [comment]
Update your gradle dependency to 
```'compile 'com.codemybrainsout.placesearchdialog:placesearch:1.0.1'```
and use ```.setLatLngBounds(BOUNDS)```
