### ISSUE TITLE
Change string values

### ISSUE THREAD

**Issue by ghost** [codemybrainsout/PlaceSearchDialog#2]
Hello , this dialog looks awesome. I got a question before using it : Is it possible to change those string values like "enter location" , "ok", "cancel" ? I would like them displayed in another language =) Thanks

and a side question:

<meta-data android:name="com.google.android.geo.API_KEY"
            android:value="YOUR_API_KEY" />

What is this ? Do I need an api key for using location API's?

**Comment by ahulr** [comment]
Added support for customizing dialog in the latest version. Update your gradle dependency to-

```compile 'com.codemybrainsout.placesearchdialog:placesearch:1.0.1'```
