### ISSUE TITLE
locationName(String) is nowhere to be found

### ISSUE THREAD

**Issue by braulio94** [codemybrainsout/PlaceSearchDialog#3]
java.lang.NoSuchMethodError: 
No static method zzb(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; 
in class Lcom/google/android/gms/common/internal/zzaa; 
or its super classes (declaration of 'com.google.android.gms.common.internal.zzaa' 
appears in /data/data/com.braulio.cassule.designfocus/files/instant-run/dex/slice-com.google.android.gms-play-services-basement-9.6.1_a90f1e9ce9bdbcb44b81e93fad4cebe23b3cf46c-classes.dex)

**Comment by ahulr** [comment]
Fixed in v1.0.1
